### ISSUE TITLE
bad imports prevent building & testing

### ISSUE THREAD

**Issue by mlsquires** [pschlump/socketio#1]
There are three places with bad imports:

1. in handler.go it imports github.com/Sirupsen/logrus, but that package has been updated to be all lower case (https://github.com/sirupsen/logrus)

1. in engineio/polling/server_test.go it imports "github.com/pschlmp/socketio/engineio" (typo in your repo name)

1. in engineio/server_conn_test.go it imports "github.com/pschlump/scoketio" - typo in repo name

I've got those fixed and will submit a PR.

**Comment by pschlump** [comment]
fixed.

thanks for finding and making a PR!
